name: ci

on:
  repository_dispatch:
#  release:
#    types: published
  schedule:
    - cron: 0/7 * * * * 
  watch:
    types: started
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: download
        run: |
          git config --local user.email "justjavac@gmail.com"
          git config --local user.name "迷渡"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          ./bin/youtube-dl --config-location config.txt
          git add .
          git commit -m "download youtube video"
          git push
